import Link from 'next/link';
import { requireAdminPage } from '@/lib/admin-auth';
import { db } from '@/lib/db';
import { AdminShell } from '@/components/admin-shell';
import { business } from '@/lib/config';
import { dateAtZone } from '@/lib/date';
export const dynamic = 'force-dynamic';
export default async function AdminDashboard() {
  const admin = await requireAdminPage();
  const today = new Date(`${dateAtZone(new Date(),business.timeZone)}T00:00:00.000Z`); const tomorrow = new Date(today.getTime()+86400000);
  const [total,todayCount,confirmed,assigned,active,completed,cancelled,available,recent,todays] = await Promise.all([
    db.booking.count(), db.booking.count({where:{serviceDate:today}}), db.booking.count({where:{status:'CONFIRMED'}}), db.booking.count({where:{status:'ASSIGNED'}}), db.booking.count({where:{status:{in:['WORKER_ON_THE_WAY','WORK_STARTED']}}}), db.booking.count({where:{status:'WORK_COMPLETED'}}), db.booking.count({where:{status:'CANCELLED'}}), db.worker.count({where:{status:'AVAILABLE'}}),
    db.booking.findMany({take:6,orderBy:{createdAt:'desc'},include:{customer:true,service:true,assignedWorker:{select:{fullName:true}}}}),
    db.booking.findMany({where:{serviceDate:{gte:today,lt:tomorrow}},orderBy:{serviceTime:'asc'},take:8,include:{customer:true,service:true,assignedWorker:{select:{fullName:true}}}}),
  ]);
  const cards=[['Total bookings',total,'/admin/bookings'],["Today's bookings",todayCount,'/admin/bookings'],['Confirmed',confirmed,'/admin/bookings?status=CONFIRMED'],['Assigned',assigned,'/admin/bookings?status=ASSIGNED'],['Active jobs',active,'/admin/bookings'],['Completed',completed,'/admin/bookings?status=WORK_COMPLETED'],['Cancelled',cancelled,'/admin/bookings?status=CANCELLED']];
  const rows=(items: typeof recent)=>items.map(b=><tr key={b.id}><td><b>{b.bookingNumber}</b></td><td>{b.customer.fullName}<small>{b.customer.phone}</small></td><td>{b.service.name}</td><td>{b.serviceTime}</td><td>{b.assignedWorker?.fullName||'Unassigned'}</td><td><span className={`admin-pill pill-${b.status.toLowerCase()}`}>{b.status.replaceAll('_',' ')}</span></td><td><Link href={`/admin/bookings/${b.id}`}>View ↗</Link></td></tr>);
  return <AdminShell name={admin.name} email={admin.email}><div className="admin-page-title"><div><span className="eyebrow">Operations overview</span><h1>Good day, {admin.name.split(' ')[0]}.</h1><p>Here’s what’s happening across ONECREW today.</p></div><Link href="/admin/bookings/new" className="button button-primary">＋ Create booking</Link></div><div className="admin-stat-grid">{cards.map(([label,value,href])=><Link className="admin-stat-card" href={href as string} key={label as string}><span>{label}</span><b>{value as number}</b><small>Open list ↗</small></Link>)}</div><div className="admin-lower-grid"><section className="admin-panel"><div className="admin-panel-head"><div><span className="eyebrow">Today</span><h2>Today’s jobs</h2></div><Link href="/admin/bookings">All bookings ↗</Link></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Booking</th><th>Customer</th><th>Service</th><th>Time</th><th>Worker</th><th>Status</th><th></th></tr></thead><tbody>{todays.length?rows(todays):<tr><td colSpan={7} className="admin-empty">No bookings scheduled today.</td></tr>}</tbody></table></div></section><aside className="admin-side-stack"><section className="admin-panel available-panel"><span className="eyebrow">On the roster</span><h2>Available workers</h2><b className="available-count">{available}</b><p>workers currently available to assign</p><Link href="/admin/workers">View workers ↗</Link></section><section className="admin-panel shortcuts-panel"><span className="eyebrow">Quick actions</span><Link href="/admin/bookings/new">＋ Create a booking <b>→</b></Link><Link href="/admin/workers">＋ Add a worker <b>→</b></Link><Link href="/admin/applications">Review new applications <b>→</b></Link></section></aside></div><section className="admin-panel recent-panel"><div className="admin-panel-head"><div><span className="eyebrow">Latest updates</span><h2>Recent bookings</h2></div><Link href="/admin/bookings">All bookings ↗</Link></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Booking</th><th>Customer</th><th>Service</th><th>Time</th><th>Worker</th><th>Status</th><th></th></tr></thead><tbody>{recent.length?rows(recent):<tr><td colSpan={7} className="admin-empty">No bookings yet. Create one after payment is verified.</td></tr>}</tbody></table></div></section></AdminShell>;
}
