'use client';
import { useCallback, useEffect, useState } from 'react';
type Worker={id:string;fullName:string;phone:string;whatsapp:string;profilePhoto:string|null;workerType:string;skills:string[];experience:number|null;serviceAreas:string[];availability:string;status:string;_count?:{bookings:number}};
const workerTypes=[['SKILLED_WORKER','Skilled worker'],['GENERAL_LABOUR','General labour'],['TEMPORARY_WORKER','Temporary worker'],['EMERGENCY_WORKER','Emergency worker'],['OTHER','Other']];
const appStatuses=['NEW','REVIEWING','CONTACTED','APPROVED','REJECTED']; const pretty=(x:string)=>x.replaceAll('_',' ');
export function WorkerManager(){
  const [workers,setWorkers]=useState<Worker[]>([]),[q,setQ]=useState(''),[error,setError]=useState(''),[show,setShow]=useState(false),[editing,setEditing]=useState<Worker|null>(null),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const r=await fetch(`/api/admin/workers?q=${encodeURIComponent(q)}`);const b=await r.json();if(!r.ok)throw new Error(b.error);setWorkers(b);},[q]);
  useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const photo=f.get('profilePhoto');const body={fullName:f.get('fullName'),phone:f.get('phone'),whatsapp:f.get('whatsapp'),workerType:f.get('workerType'),skills:String(f.get('skills')).split(',').map(x=>x.trim()).filter(Boolean),serviceAreas:String(f.get('serviceAreas')).split(',').map(x=>x.trim()).filter(Boolean),experience:f.get('experience'),availability:f.get('availability')};try{const r=await fetch(editing?`/api/admin/workers/${editing.id}`:'/api/admin/workers',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error);const id=editing?.id||b.id;if(photo instanceof File&&photo.size){const upload=new FormData();upload.set('photo',photo);const pr=await fetch(`/api/admin/workers/${id}/photo`,{method:'POST',body:upload});const pb=await pr.json();if(!pr.ok){setEditing(null);setShow(false);setError(`Worker profile saved. Photo upload failed: ${pb.error}`);await load();return;}}setEditing(null);setShow(false);await load();}catch(e){setError(e instanceof Error?e.message:'Could not save worker.');}finally{setBusy(false);}}
  async function status(w:Worker,value:string){setError('');try{const r=await fetch(`/api/admin/workers/${w.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:value})});const b=await r.json();if(!r.ok)throw new Error(b.error);await load();}catch(e){setError(e instanceof Error?e.message:'Could not update status.');}}
  const form=(w?:Worker|null)=><form className="admin-inline-form" onSubmit={submit}><div className="admin-panel-head"><h2>{w?'Edit worker':'Add a worker'}</h2><button type="button" className="admin-quiet-button" onClick={()=>{setShow(false);setEditing(null);}}>Close ×</button></div>{w?.profilePhoto&&<img className="worker-edit-photo" src={`/api/admin/workers/${w.id}/photo`} alt={`${w.fullName} profile`}/>}<div className="admin-field-grid"><label>Full name *<input name="fullName" required defaultValue={w?.fullName}/></label><label>Phone *<input name="phone" type="tel" required defaultValue={w?.phone}/></label><label>WhatsApp *<input name="whatsapp" type="tel" required defaultValue={w?.whatsapp}/></label><label>Worker type *<select name="workerType" defaultValue={w?.workerType||'GENERAL_LABOUR'}>{workerTypes.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Skills, comma separated<input name="skills" defaultValue={w?.skills.join(', ')}/></label><label>Service areas, comma separated<input name="serviceAreas" defaultValue={w?.serviceAreas.join(', ')}/></label><label>Experience (years)<input name="experience" type="number" min="0" max="60" defaultValue={w?.experience??''}/></label><label>Availability<input name="availability" defaultValue={w?.availability||'On demand'}/></label><label>Profile photo<input name="profilePhoto" type="file" accept="image/jpeg,image/png,image/webp"/><small>Optional image up to 8 MB.</small></label></div>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button button-primary" disabled={busy}>{busy?'Saving…':w?'Save worker':'Add worker'} ↗</button></form>;
  return <><div className="admin-page-title"><div><span className="eyebrow">The ONECREW network</span><h1>Workers</h1><p>Manage worker profiles, skills, service areas and availability.</p></div><button className="button button-primary" onClick={()=>{setEditing(null);setShow(!show);}}>＋ Add worker</button></div>{error&&<div className="admin-error">{error}</div>}{(show||editing)&&form(editing)}<div className="admin-filter-bar"><input placeholder="Search name, phone or skill" value={q} onChange={e=>setQ(e.target.value)}/><span className="admin-filter-count">{workers.length} workers</span></div><section className="admin-panel"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Worker</th><th>Type & skills</th><th>Service areas</th><th>Experience</th><th>Availability</th><th>Current status</th><th>Jobs</th><th>Actions</th></tr></thead><tbody>{workers.length?workers.map(w=><tr key={w.id}><td>{w.profilePhoto&&<img className="worker-table-photo" src={`/api/admin/workers/${w.id}/photo`} alt=""/>}<b>{w.fullName}</b><small>{w.phone}</small></td><td>{pretty(w.workerType)}<small>{w.skills.join(', ')||'No skills listed'}</small></td><td>{w.serviceAreas.join(', ')||'—'}</td><td>{w.experience===null?'—':`${w.experience} years`}</td><td>{w.availability}</td><td><span className={`admin-pill pill-${w.status.toLowerCase()}`}>{w.status}</span></td><td>{w._count?.bookings||0}</td><td><div className="admin-row-actions"><button onClick={()=>{setEditing(w);setShow(false);}}>Edit</button><select aria-label={`Set ${w.fullName} status`} value={w.status} onChange={e=>void status(w,e.target.value)}>{['AVAILABLE','BUSY','OFFLINE','INACTIVE'].map(s=><option key={s}>{s}</option>)}</select></div></td></tr>):<tr><td colSpan={8} className="admin-empty">No workers found. Add a worker profile to get started.</td></tr>}</tbody></table></div></section></>;
}

type Application={id:string;fullName:string;phone:string;whatsapp:string;email:string|null;location:string;workerType:string;primarySkill:string;experience:number|null;preferredArea:string|null;availability:string;previousExperience:string|null;languages:string|null;additionalSkills:string|null;status:string;createdAt:string;files:{id:string;originalName:string;mimeType:string;size:number}[];convertedWorker?:{id:string;fullName:string}|null};
export function ApplicationManager(){
  const [apps,setApps]=useState<Application[]>([]),[status,setStatus]=useState(''),[q,setQ]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState('');
  const load=useCallback(async()=>{const p=new URLSearchParams();if(status)p.set('status',status);if(q)p.set('q',q);const r=await fetch(`/api/admin/applications?${p}`);const b=await r.json();if(!r.ok)throw new Error(b.error);setApps(b);},[q,status]);
  useEffect(()=>{void load().catch(e=>setError(e.message));},[load]);
  async function change(id:string,newStatus:string){setBusy(id);setError('');try{const r=await fetch('/api/admin/applications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:newStatus})});const b=await r.json();if(!r.ok)throw new Error(b.error);await load();}catch(e){setError(e instanceof Error?e.message:'Update failed.');}finally{setBusy('');}}
  async function convert(id:string){setBusy(id);setError('');try{const r=await fetch(`/api/admin/applications/${id}/convert`,{method:'POST'});const b=await r.json();if(!r.ok)throw new Error(b.error);await load();}catch(e){setError(e instanceof Error?e.message:'Could not create worker profile.');}finally{setBusy('');}}
  return <><div className="admin-page-title"><div><span className="eyebrow">People joining the network</span><h1>Career applications</h1><p>Review applications and convert approved candidates into worker profiles.</p></div><span className="admin-total-chip">{apps.filter(a=>a.status==='NEW').length} new</span></div><div className="admin-filter-bar"><input placeholder="Search name, phone or skill" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{appStatuses.map(s=><option key={s}>{s}</option>)}</select></div>{error&&<div className="admin-error">{error}</div>}<div className="application-admin-list">{apps.length?apps.map(a=><article className="admin-panel application-admin-card" key={a.id}><div className="application-admin-head"><div><span className="eyebrow">{new Date(a.createdAt).toLocaleDateString('en-IN')} · {pretty(a.workerType)}</span><h2>{a.fullName}</h2><p>{a.primarySkill}{a.experience!==null?` · ${a.experience} years experience`:''}</p></div><select value={a.status} disabled={busy===a.id} onChange={e=>void change(a.id,e.target.value)}>{appStatuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="application-admin-facts"><span><small>Phone / WhatsApp</small>{a.phone} / {a.whatsapp}</span><span><small>Email & location</small>{a.email||'—'} · {a.location}</span><span><small>Area & availability</small>{a.preferredArea||a.location} · {a.availability}</span><span><small>Languages</small>{a.languages||'—'}</span></div>{(a.previousExperience||a.additionalSkills)&&<p className="application-notes">{a.previousExperience&&<><b>Experience:</b> {a.previousExperience} </>}{a.additionalSkills&&<><b>Additional skills:</b> {a.additionalSkills}</>}</p>}{a.files.length>0&&<div className="application-files"><small>Private attachments</small>{a.files.map(f=><a key={f.id} href={`/api/admin/applications/${a.id}/files/${f.id}`}>{f.originalName} ↓</a>)}</div>}<div className="application-admin-actions">{a.status==='NEW'&&<button onClick={()=>void change(a.id,'REVIEWING')}>Mark reviewing</button>}{a.status!=='APPROVED'&&a.status!=='REJECTED'&&<><button onClick={()=>void change(a.id,'CONTACTED')}>Mark contacted</button><button onClick={()=>void change(a.id,'APPROVED')}>Approve</button><button className="reject-action" onClick={()=>void change(a.id,'REJECTED')}>Reject</button></>}{a.status==='APPROVED'&&!a.convertedWorker&&<button className="convert-action" disabled={busy===a.id} onClick={()=>void convert(a.id)}>Convert to worker</button>}{a.convertedWorker&&<span className="converted-worker">Worker profile created: {a.convertedWorker.fullName}</span>}</div></article>):<div className="admin-panel admin-empty">No applications match this filter yet.</div>}</div></>;
}
